<template><div><h1 id="文章" tabindex="-1"><a class="header-anchor" href="#文章"><span>文章</span></a></h1>
<h2 id="题解" tabindex="-1"><a class="header-anchor" href="#题解"><span>题解</span></a></h2>
<h3 id="p2734-usaco3-3-游戏-a-game" tabindex="-1"><a class="header-anchor" href="#p2734-usaco3-3-游戏-a-game"><span>P2734 [USACO3.3] 游戏 A Game</span></a></h3>
<p>这是一道非常经典的区间动态规划题目，但是可以用 <span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>d</mi><mi>f</mi><mi>s</mi></mrow><annotation encoding="application/x-tex">dfs</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:0.69444em;"></span><span class="strut bottom" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span><span class="base textstyle uncramped"><span class="mord mathit">d</span><span class="mord mathit" style="margin-right:0.10764em;">f</span><span class="mord mathit">s</span></span></span></span>。<s>十分锻炼人的思路</s>
具体的在<a href="P2734%20%5BUSACO3.3%5D%20%E6%B8%B8%E6%88%8F%20A%20Game">这里</a></p>
<h3 id="p2979-usaco10jan-cheese-towers-s" tabindex="-1"><a class="header-anchor" href="#p2979-usaco10jan-cheese-towers-s"><span>P2979 [USACO10JAN] Cheese Towers S</span></a></h3>
<p>非常典型的背包类的问题
题解在<a href="P2979%20%5BUSACO10JAN%5D%20Cheese%20Towers%20S">这里</a></p>
<h3 id="p1131-zjoi2007-时态同步" tabindex="-1"><a class="header-anchor" href="#p1131-zjoi2007-时态同步"><span>P1131 [ZJOI2007] 时态同步</span></a></h3>
<p>较为简单的树上动态规划题目，<span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>d</mi><mi>f</mi><mi>s</mi></mrow><annotation encoding="application/x-tex">dfs</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:0.69444em;"></span><span class="strut bottom" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span><span class="base textstyle uncramped"><span class="mord mathit">d</span><span class="mord mathit" style="margin-right:0.10764em;">f</span><span class="mord mathit">s</span></span></span></span> 为最好思路
题解在<RouteLink to="/essays/OI/2024.10/P1131%20%5BZJOI2007%5D%20%E6%97%B6%E6%80%81%E5%90%8C%E6%AD%A5.html">这里</RouteLink></p>
<h3 id="p2736-usaco3-4-破锣摇滚-乐队-raucous-rockers" tabindex="-1"><a class="header-anchor" href="#p2736-usaco3-4-破锣摇滚-乐队-raucous-rockers"><span>P2736 [USACO3.4] “破锣摇滚”乐队 Raucous Rockers</span></a></h3>
<p>这个题目 ??难蚌,实际上 <span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>d</mi><mi>f</mi><mi>s</mi></mrow><annotation encoding="application/x-tex">dfs</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:0.69444em;"></span><span class="strut bottom" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span><span class="base textstyle uncramped"><span class="mord mathit">d</span><span class="mord mathit" style="margin-right:0.10764em;">f</span><span class="mord mathit">s</span></span></span></span> 即可,虽然这道题目是 <span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>d</mi><mi>p</mi></mrow><annotation encoding="application/x-tex">dp</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:0.69444em;"></span><span class="strut bottom" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span><span class="base textstyle uncramped"><span class="mord mathit">d</span><span class="mord mathit">p</span></span></span></span> 题目(二维背包).
题解在<RouteLink to="/essays/OI/2024.10/P2736%20%5BUSACO3.4%5D%20%E2%80%9C%E7%A0%B4%E9%94%A3%E6%91%87%E6%BB%9A%E2%80%9D%E4%B9%90%E9%98%9F%20Raucous%20Rockers.html">这里</RouteLink></p>
<h3 id="p1280-尼克的任务" tabindex="-1"><a class="header-anchor" href="#p1280-尼克的任务"><span>P1280 尼克的任务</span></a></h3>
<p>实际上就是一个很容易的 <span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>d</mi><mi>p</mi></mrow><annotation encoding="application/x-tex">dp</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:0.69444em;"></span><span class="strut bottom" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span><span class="base textstyle uncramped"><span class="mord mathit">d</span><span class="mord mathit">p</span></span></span></span> + 滑动窗口 类型的题目
题解在<RouteLink to="/essays/OI/2024.10/P1280%20%E5%B0%BC%E5%85%8B%E7%9A%84%E4%BB%BB%E5%8A%A1.html">here</RouteLink></p>
</div></template>


